### ISSUE TITLE
Compression failure in 1.1.5

### ISSUE THREAD

**Issue by jeswinsimon** [nfriedly/node-bestzip#19]
Compressing a directory using version 1.1.5 throws the following error:

> bestzip hello.zip .\payload\

> archive.bulk([
>                  ^
>
>TypeError: archive.bulk is not a function
>    at C:\Users\jeswin.simon\AppData\Roaming\npm\node_modules\bestzip\lib\bestzip.js:70:19
>    at FSReqWrap.oncomplete (fs.js:123:15)

**Environment:**
OS: Windows 10
Node 6.10.3
npm 3.10.10

**Comment by jeswinsimon** [comment]
As per the [changelog](https://archiverjs.com/docs/#changelog) of Archiver, the `bulk` method was removed in version 2.0.0. 
bestzip 1.1.5 upgarded to Archiver 2.1.1 whereas the previous version uses Archiver 0.21.0.

**Comment by aramirez-asuresoftware** [comment]
Observed the same issues as @jeswinsimon - OS independent as expected. Recreated the issue on CentOS.

**Comment by Lampei** [comment]
Yup, this was why in this issue https://github.com/nfriedly/node-bestzip/issues/10 I had to use a different method.  Until the code is updated to use something other than "bulk" we are still reliant on the older archiver.

**Comment by nfriedly** [comment]
Hey everyone, sorry about this. There was a to update to the latest version of archiver yesterday, and the tests passed, but it turned out that we didn't have any tests covering the 'bulk' path. I added a test suite for that, confirmed that it worked with the old archiver@0.21 and failed as expected with the archiver@latest. Then I tested on archiver@1 and it passed there.

So, v1.1.6 will be out once CI finishes that should work the same as v1.1.4, except hopefully without the security issue that #18 was trying to resolve.
